// Generated by CoffeeScript 1.7.1
(function() {
  var EventService, RoomOverlay;

  EventService = require('./EventService.coffee');

  module.exports = RoomOverlay = (function() {
    var OFFALPHA;

    OFFALPHA = 0.8;

    function RoomOverlay(roomModel) {
      var gfx;
      this.roomModel = roomModel;
      this._container = new PIXI.Container();
      this._container.position.x = this.roomModel.x;
      gfx = new PIXI.Graphics();
      gfx.beginFill(0x000000);
      gfx.drawRect(0, 0, this.roomModel.width, 256);
      gfx.endFill();
      gfx.alpha = OFFALPHA;
      this._container.addChild(gfx);
      EventService.on('objectClicked', (function(_this) {
        return function(itemModel) {
          if (itemModel.name === _this.roomModel["switch"]) {
            return gfx.alpha = gfx.alpha === OFFALPHA ? 0 : OFFALPHA;
          }
        };
      })(this));
    }

    return RoomOverlay;

  })();

}).call(this);
